package api

import (
	"net/http"
	"strings"
)

// envelopeMiddleware wraps next so that 404 / 405 responses produced by
// the stdlib http.ServeMux (text/plain bodies generated by
// http.NotFound and the mux's automatic Method Not Allowed handler)
// are rewritten to the package's canonical JSON ErrorEnvelope. Any 404
// / 405 response whose Content-Type is already application/json is
// left alone — handler-driven 404s (e.g. writeNotFound) and intentional
// JSON 405s (none today) pass through unchanged so their typed
// details[] payloads survive.
//
// Implementation note: the interceptor decides on WriteHeader (the
// first call wins; later calls are dropped, matching net/http's own
// behavior). When the override fires, the inner handler's subsequent
// Write calls are discarded so the text/plain body never reaches the
// wire. When the override does not fire, the interceptor is a
// transparent passthrough with no buffering — /metrics' streaming
// payload, large list responses, and SSE-shaped responses (none today
// but reserved) all work without per-byte allocation.
func envelopeMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		i := &errorEnvelopeInterceptor{inner: w}
		next.ServeHTTP(i, r)
		if !i.headerWritten {
			// No handler in the chain wrote a status. The inner
			// ResponseWriter would default to 200 on first Write;
			// we call WriteHeader explicitly so a no-op handler
			// path still produces a well-formed response.
			i.WriteHeader(http.StatusOK)
		}
	})
}

type errorEnvelopeInterceptor struct {
	inner          http.ResponseWriter
	headerWritten  bool
	suppressBody   bool
	overrodeStatus int
}

func (i *errorEnvelopeInterceptor) Header() http.Header {
	return i.inner.Header()
}

func (i *errorEnvelopeInterceptor) WriteHeader(code int) {
	if i.headerWritten {
		return
	}
	i.headerWritten = true

	if (code == http.StatusNotFound || code == http.StatusMethodNotAllowed) &&
		!isJSONContentType(i.inner.Header().Get("Content-Type")) {
		// Override: replace the stdlib mux's text/plain body with
		// our JSON envelope. Preserve Allow (mux sets it on 405)
		// so RFC 7231 §6.5.5 compliance is unchanged. Drop
		// Content-Length — we are about to write a different body.
		i.inner.Header().Set("Content-Type", "application/json")
		i.inner.Header().Del("Content-Length")
		i.inner.WriteHeader(code)
		i.suppressBody = true
		i.overrodeStatus = code
		_, _ = i.inner.Write(envelopeBody(code))
		return
	}

	i.inner.WriteHeader(code)
}

func (i *errorEnvelopeInterceptor) Write(b []byte) (int, error) {
	if !i.headerWritten {
		i.WriteHeader(http.StatusOK)
	}
	if i.suppressBody {
		return len(b), nil
	}
	return i.inner.Write(b)
}

// Flush forwards the http.Flusher interface so streaming responses
// (e.g. SSE, /metrics scraping) work through the wrapper. The inner
// ResponseWriter from net/http's default server implements Flusher.
func (i *errorEnvelopeInterceptor) Flush() {
	if i.suppressBody {
		return
	}
	if f, ok := i.inner.(http.Flusher); ok {
		f.Flush()
	}
}

func isJSONContentType(ct string) bool {
	if ct == "" {
		return false
	}
	// Trim parameters such as "; charset=utf-8".
	if idx := strings.IndexByte(ct, ';'); idx >= 0 {
		ct = ct[:idx]
	}
	return strings.EqualFold(strings.TrimSpace(ct), "application/json")
}

// envelopeBody returns the canonical JSON body for a stdlib-generated
// 404 / 405. Marshalling is hand-rolled so the wrapper stays
// allocation-free in the common case (a long-lived []byte literal) and
// avoids pulling encoding/json into the hot path.
func envelopeBody(status int) []byte {
	switch status {
	case http.StatusNotFound:
		return []byte(`{"error":{"code":"not_found","message":"route not found"}}` + "\n")
	case http.StatusMethodNotAllowed:
		return []byte(`{"error":{"code":"method_not_allowed","message":"method not allowed"}}` + "\n")
	}
	return nil
}
